package com.youranxue.domain.mapper;

import com.youranxue.domain.model.ChapterMst;
import com.youranxue.domain.model.ChapterMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChapterMstMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	long countByExample(ChapterMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	int deleteByExample(ChapterMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	int deleteByPrimaryKey(Integer chapterId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	int insert(ChapterMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	int insertSelective(ChapterMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	List<ChapterMst> selectByExample(ChapterMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	ChapterMst selectByPrimaryKey(Integer chapterId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	int updateByExampleSelective(@Param("record") ChapterMst record, @Param("example") ChapterMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	int updateByExample(@Param("record") ChapterMst record, @Param("example") ChapterMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	int updateByPrimaryKeySelective(ChapterMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.chapter_mst
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	int updateByPrimaryKey(ChapterMst record);
}