package com.youranxue.domain.mapper;

import com.youranxue.domain.model.ImgMst;
import com.youranxue.domain.model.ImgMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgMstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    long countByExample(ImgMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int deleteByExample(ImgMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int insert(ImgMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int insertSelective(ImgMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    List<ImgMst> selectByExample(ImgMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    ImgMst selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int updateByExampleSelective(@Param("record") ImgMst record, @Param("example") ImgMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int updateByExample(@Param("record") ImgMst record, @Param("example") ImgMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int updateByPrimaryKeySelective(ImgMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int updateByPrimaryKey(ImgMst record);
}