package com.youranxue.domain.mapper;

import com.youranxue.domain.model.MyBooks;
import com.youranxue.domain.model.MyBooksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyBooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    long countByExample(MyBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int deleteByExample(MyBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int deleteByPrimaryKey(Integer myBookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int insert(MyBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int insertSelective(MyBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    List<MyBooks> selectByExample(MyBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    MyBooks selectByPrimaryKey(Integer myBookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int updateByExampleSelective(@Param("record") MyBooks record, @Param("example") MyBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int updateByExample(@Param("record") MyBooks record, @Param("example") MyBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int updateByPrimaryKeySelective(MyBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youranxue.my_books
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    int updateByPrimaryKey(MyBooks record);
}