package com.youranxue.domain.model;

import java.util.Date;

public class BookMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.book_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private Integer bookId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.grade_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private Integer gradeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.book_name
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private String bookName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.isbn
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private String isbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.subject_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private Integer subjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.semester_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private Integer semesterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.publisher_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private Integer publisherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.create_date
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.update_date
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.update_user
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.book_mst.del_flg
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	private Short delFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.book_id
	 * @return  the value of youranxue.book_mst.book_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public Integer getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.book_id
	 * @param bookId  the value for youranxue.book_mst.book_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.grade_id
	 * @return  the value of youranxue.book_mst.grade_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public Integer getGradeId() {
		return gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.grade_id
	 * @param gradeId  the value for youranxue.book_mst.grade_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.book_name
	 * @return  the value of youranxue.book_mst.book_name
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public String getBookName() {
		return bookName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.book_name
	 * @param bookName  the value for youranxue.book_mst.book_name
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.isbn
	 * @return  the value of youranxue.book_mst.isbn
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public String getIsbn() {
		return isbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.isbn
	 * @param isbn  the value for youranxue.book_mst.isbn
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.subject_id
	 * @return  the value of youranxue.book_mst.subject_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public Integer getSubjectId() {
		return subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.subject_id
	 * @param subjectId  the value for youranxue.book_mst.subject_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.semester_id
	 * @return  the value of youranxue.book_mst.semester_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public Integer getSemesterId() {
		return semesterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.semester_id
	 * @param semesterId  the value for youranxue.book_mst.semester_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setSemesterId(Integer semesterId) {
		this.semesterId = semesterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.publisher_id
	 * @return  the value of youranxue.book_mst.publisher_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public Integer getPublisherId() {
		return publisherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.publisher_id
	 * @param publisherId  the value for youranxue.book_mst.publisher_id
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setPublisherId(Integer publisherId) {
		this.publisherId = publisherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.create_date
	 * @return  the value of youranxue.book_mst.create_date
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.create_date
	 * @param createDate  the value for youranxue.book_mst.create_date
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.update_date
	 * @return  the value of youranxue.book_mst.update_date
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.update_date
	 * @param updateDate  the value for youranxue.book_mst.update_date
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.update_user
	 * @return  the value of youranxue.book_mst.update_user
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.update_user
	 * @param updateUser  the value for youranxue.book_mst.update_user
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.book_mst.del_flg
	 * @return  the value of youranxue.book_mst.del_flg
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public Short getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.book_mst.del_flg
	 * @param delFlg  the value for youranxue.book_mst.del_flg
	 * @mbg.generated  Fri Oct 06 20:59:03 JST 2017
	 */
	public void setDelFlg(Short delFlg) {
		this.delFlg = delFlg;
	}
}