package com.youranxue.domain.model;

import java.util.Date;

public class MyBooks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.my_books.my_book_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    private Integer myBookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.my_books.user_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.my_books.book_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.my_books.create_date
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.my_books.update_date
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.my_books.update_user
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.my_books.del_flg
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    private Short delFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.my_books.my_book_id
     *
     * @return the value of youranxue.my_books.my_book_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public Integer getMyBookId() {
        return myBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.my_books.my_book_id
     *
     * @param myBookId the value for youranxue.my_books.my_book_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public void setMyBookId(Integer myBookId) {
        this.myBookId = myBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.my_books.user_id
     *
     * @return the value of youranxue.my_books.user_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.my_books.user_id
     *
     * @param userId the value for youranxue.my_books.user_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.my_books.book_id
     *
     * @return the value of youranxue.my_books.book_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.my_books.book_id
     *
     * @param bookId the value for youranxue.my_books.book_id
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.my_books.create_date
     *
     * @return the value of youranxue.my_books.create_date
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.my_books.create_date
     *
     * @param createDate the value for youranxue.my_books.create_date
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.my_books.update_date
     *
     * @return the value of youranxue.my_books.update_date
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.my_books.update_date
     *
     * @param updateDate the value for youranxue.my_books.update_date
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.my_books.update_user
     *
     * @return the value of youranxue.my_books.update_user
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.my_books.update_user
     *
     * @param updateUser the value for youranxue.my_books.update_user
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.my_books.del_flg
     *
     * @return the value of youranxue.my_books.del_flg
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public Short getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.my_books.del_flg
     *
     * @param delFlg the value for youranxue.my_books.del_flg
     *
     * @mbg.generated Fri Oct 06 20:59:03 JST 2017
     */
    public void setDelFlg(Short delFlg) {
        this.delFlg = delFlg;
    }
}